name: Deploy demo to GitHub Pages

on:
  push:
    branches: [ master ]

permissions:
  contents: write

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.9
      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-
      - name: Install dependencies
        run: corepack pnpm install
      - name: Run build
        run: npm run demo:build
      - name: Deploy demo
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: packages/demo/dist
